Repository StudentTraineeCenter/stcblog, pull requests merged in 2020-12, with the labels that each got.

#48 Update _global.scss to fix heading overflow
  assets/scss/_global.scss
Labels: problem

#47 Repair Microsoft Clarity cookies
  footer.php
Labels: priority, problem

#49 Allowed .mcworld, miscellaneous tweaks
  footer.php
  functions.php
Labels: enhancement

#51 Delete linter.yml
  .github/workflows/linter.yml
Labels: problem

#54 JQuery update, fix caching of trackers
  a.json
  assets/js/jquery.min.js
  azure-pipelines.yml
  campaign-banner.php
  footer.php
  header.php
  index.php
Labels: problem

#55 Project firework
  assets/scss/_feed.scss
  backgorund-animations.php
  footer.php
Labels: enhancement

#59 Auto year
  functions.php
Labels: enhancement
