Repository StudentTraineeCenter/stcblog, pull requests merged in 2020-11, with the labels that each got.

#24 README updates
  README.md
Labels: enhancement

#31 Display dynamicly
  assets/js/main.js
Labels: problem

#34 DevOps Pipelines
  azure-pipelines.yml
Labels: priority, problem

#40 hotfix: Hide campaign bar
  campaign-banner.php
Labels: priority, problem

#43 Small updates
  assets/js/cookies-setting.js
  assets/scss/_cookiesBanner.scss
  footer.php
  functions.php
  style.css
  style.css.map
Labels: enhancement
