Repository StudentTraineeCenter/stcblog, pull requests merged in 2021-02, with the labels that each got.

#56 Setup GitPod
  .gitpod.Dockerfile
  .gitpod.yml
  conf/.bashrc.sh
  conf/apache.conf
  conf/apache.env.sh
  conf/php.ini
Labels: meta

#64 change word-break from break-all to break-word
  assets/scss/_global.scss
  style.css
  style.css.map
Labels: problem

#65 Pinned posts
  .vscode/settings.json
  assets/img/pin.svg
  assets/scss/_feed.scss
  assets/scss/style.css
  assets/scss/style.css.map
  colors.css
  colors.css.map
  index.php
  style.css
  style.css.map
Labels: enhancement

#67 Add the second Fabric UI change
  README.md
Labels: documentation

#68 Set static width to avatar
  assets/scss/_single.scss
Labels: problem

#69 Set level of title from h1 to h2 for better SEO
  author.php
Labels: problem
